- name: Setup MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Enable and start MongoDB service
      ansible.builtin.service:
        name: mongod
        enabled: true
        state: started

    - name: Allow connections from all IPs in MongoDB config
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: Restart MongoDB service
      ansible.builtin.service:
        name: mongod
        state: restarted
